<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="data.txt" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\logictier\logictier.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="data.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="data1.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Page Update="MainWindow.xaml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Page>
  </ItemGroup>

</Project>
